trigger:
- main  # Branch to trigger the pipeline

pr:
- main  # Pull requests targeting the main branch will trigger the pipeline

pool:
  vmImage: 'windows-latest'  # Choose an appropriate image based on your requirements

jobs:
- job: Build
  steps:
  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '6.0.x'  # Replace with the desired .NET 6.0 version

  - script: dotnet build --configuration Release
    displayName: 'Build the ASP.NET Core Web App'
  - task: CmdLine@2
    displayName: 'List Files in Output Directory'
  -  script: 'dir D:\a\1\s\demoapp1\bin\Release\net6.0 /s'




# Add more stages and steps for deployment if needed
